// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC3NlZdhSIsjdmH_ZO1yONQJ4Fw1-xZ_88',
    appId: '1:956782711879:web:207208107d9b2a341c4d62',
    messagingSenderId: '956782711879',
    projectId: 'e-commerce-bdc67',
    authDomain: 'e-commerce-bdc67.firebaseapp.com',
    storageBucket: 'e-commerce-bdc67.appspot.com',
    measurementId: 'G-NT28WKZ5Z2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDptGQIjCATycGAGge4czsM0XLxT7lB1DI',
    appId: '1:956782711879:android:f4bd80802f2558da1c4d62',
    messagingSenderId: '956782711879',
    projectId: 'e-commerce-bdc67',
    storageBucket: 'e-commerce-bdc67.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCla2jCupdbrbSDHbXrPLuBaXsfIQ8zPFg',
    appId: '1:956782711879:ios:e80abc0b9399779a1c4d62',
    messagingSenderId: '956782711879',
    projectId: 'e-commerce-bdc67',
    storageBucket: 'e-commerce-bdc67.appspot.com',
    iosBundleId: 'com.example.providerExample',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCla2jCupdbrbSDHbXrPLuBaXsfIQ8zPFg',
    appId: '1:956782711879:ios:064a796dce120fdd1c4d62',
    messagingSenderId: '956782711879',
    projectId: 'e-commerce-bdc67',
    storageBucket: 'e-commerce-bdc67.appspot.com',
    iosBundleId: 'com.example.providerExample.RunnerTests',
  );
}
